version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"    
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes:
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    container_name: backend
    environment:
      - DEBUG=True
    depends_on:
      - db  

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "5000:80"
      - "25:25"
      - "80:80"
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - serverOption__HostName=smtp4dev
volumes:
  smtp4dev-data: