services:
  - type: web
    name: marjanrezaei-store
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - fromDatabase:
          name: marjan-db
          property: connectionString
          key: DATABASE_URL

databases:
  - name: marjan-db
    databaseName: marjan
    user: marjan
